services:
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fraud
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      F_FLAG: ${F_FLAG}
    ports:
      - "${F_PORT}:80"
    volumes:
      - ./fraud:/var/www/html

  robot:
    build:
      context: .
      dockerfile: Dockerfile-robot
    volumes:
      - ./robot:/app