services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      F_FLAG: ${F_FLAG}
    ports:
      - "${F_PORT}:80"
    volumes:
      - ./fraud:/var/www/html
    command: ["sh","-c","echo flag:x:1001:1001::$F_FLAG:/bin/sh >> /etc/passwd&&apache2-foreground"]